fitting3K = DataFrame(fittingType = [	"	PIPE	",
	"	ELL-THD-STD	",
	"	ELL-THD-LR	",
	"	ELL-FLG-RD1	",
	"	ELL-FLG-RD2	",
	"	ELL-FLG-RD4	",
	"	ELL-FLG-RD6	",
	"	ELL-MIT-1	",
	"	ELL-MIT-2	",
	"	EL-MIT-3	",
	"	EL45-THD-STD	",
	"	EL45-LR	",
	"	EL45-MIT-1	",
	"	EL45-MIT-2	",
	"	EL180-THD-1	",
	"	EL180-FLG-RD1	",
	"	EL180-FLG-RD15	",
	"	TEE-THD-RD1	",
	"	TEE-THD-RD15	",
	"	TEE-FLG	",
	"	TEE-STUB	",
	"	TEE-THD-THRU	",
	"	TEE-FLG-THRU	",
	"	TEE-STUB-THRU	",
	"	VALVE-ANGLE-45-FULL	",
	"	VALVE-ANGLE-90-FULL	",
	"	VALVE-GLOBE-STD-B1	",
	"	VALVE-PLUG-BRANCH	",
	"	VALVE-PLUG-THRU	",
	"	VALVE-PLUG-3WAY-THRU	",
	"	VALVE-GATE-STD-B1	",
	"	VALVE-BALL-STD-B1	",
	"	VALVE-DIAPH-DAM	",
	"	VALVE-CHECK-SWING	",
	"	VALVE-CHECK-LIFT	",
	"	ENTRANCE-NON-RECOVER	",
	"	EXIT-NON-RECOVER	"],
Description = [	"	PipePipePipe	",
	"	Elbow - 90 DegreeThreaded-Standardr/D = 1	",
	"	Elbow - 90 DegreeThreaded Long Radiusr/D = 1.5	",
	"	Elbow - 90 DegreeFlanged Welded Bendr/D = 1	",
	"	Elbow - 90 DegreeFlanged Welded Bendr/D = 2	",
	"	Elbow - 90 DegreeFlanged Welded Bendr/D = 4	",
	"	Elbow - 90 DegreeFlanged Welded Bendr/D = 6	",
	"	Elbow - 90 DegreeMitered 1 Weld 90 Degree	",
	"	Elbow - 90 DegreeMitered 2 Welds 45 Degree	",
	"	Elbow - 90 DegreeMitered 3 Welds 30 Degree	",
	"	Elbow - 45 DegreeThreaded Standardr/D = 1	",
	"	Elbow - 45 DegreeLong Radiusr/D = 1.5	",
	"	Elbow - 45 DegreeMitered 1 Weld 45 Degree	",
	"	Elbow - 45 DegreeMitered 2 Welds 22.5 Degree	",
	"	Elbows - 180 DegreeThreaded Close Return Bendr/D = 1	",
	"	Elbows - 180 DegreeFlangedr/D = 1	",
	"	Elbows - 180 DegreeAllr/D = 1.5	",
	"	TEEThreadedr/D = 1	",
	"	TEEThreadedr/D = 1.5	",
	"	TEEFlangedr/D = 1	",
	"	TEEStub-in Branch	",
	"	TEERun Through Threadedr/D = 1	",
	"	TEEFlangedr/D = 1	",
	"	TEEStub-in Branch	",
	"	ValveAngle - 45 DegreeFull Line Size b = 1	",
	"	ValveAngle - 90 DegreeFull Line Size b = 1	",
	"	ValveGlobeStandard b = 1	",
	"	ValvePlugBranch Flow	",
	"	ValvePlugStraight Through	",
	"	ValvePlugThree-Way (flow through)	",
	"	ValveGateStandard b = 1	",
	"	ValveBallStandard b = 1	",
	"	ValveDiaphragmDam-Type	",
	"	ValveSwing CheckVmin = 35r-1/2	",
	"	ValveLift CheckVmin = 40r-1/2	",
	"	InletNon-recoverable	",
	"	ExitNon-recoverable	"],
Fitting = [	"	Pipe	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 90 Degree	",
	"	Elbow - 45 Degree	",
	"	Elbow - 45 Degree	",
	"	Elbow - 45 Degree	",
	"	Elbow - 45 Degree	",
	"	Elbows - 180 Degree	",
	"	Elbows - 180 Degree	",
	"	Elbows - 180 Degree	",
	"	TEE	",
	"	TEE	",
	"	TEE	",
	"	TEE	",
	"	TEE	",
	"	TEE	",
	"	TEE	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Valve	",
	"	Inlet	",
	"	Exit	"],
Type = [	"	Pipe	",
	"	Threaded-Standard	",
	"	Threaded Long Radius	",
	"	Flanged Welded Bend	",
	"	Flanged Welded Bend	",
	"	Flanged Welded Bend	",
	"	Flanged Welded Bend	",
	"	Mitered 1 Weld 90 Degree	",
	"	Mitered 2 Welds 45 Degree	",
	"	Mitered 3 Welds 30 Degree	",
	"	Threaded Standard	",
	"	Long Radius	",
	"	Mitered 1 Weld 45 Degree	",
	"	Mitered 2 Welds 22.5 Degree	",
	"	Threaded Close Return Bend	",
	"	Flanged	",
	"	All	",
	"	Threaded	",
	"	Threaded	",
	"	Flanged	",
	"	Stub-in Branch	",
	"	Run Through Threaded	",
	"	Flanged	",
	"	Stub-in Branch	",
	"	Angle - 45 Degree	",
	"	Angle - 90 Degree	",
	"	Globe	",
	"	Plug	",
	"	Plug	",
	"	Plug	",
	"	Gate	",
	"	Ball	",
	"	Diaphragm	",
	"	Swing Check	",
	"	Lift Check	",
	"		",
	"		"],
Geometry = [	"	Pipe	",
	"	r/D = 1	",
	"	r/D = 1.5	",
	"	r/D = 1	",
	"	r/D = 2	",
	"	r/D = 4	",
	"	r/D = 6	",
	"		",
	"		",
	"		",
	"	r/D = 1	",
	"	r/D = 1.5	",
	"		",
	"		",
	"	r/D = 1	",
	"	r/D = 1	",
	"	r/D = 1.5	",
	"	r/D = 1	",
	"	r/D = 1.5	",
	"	r/D = 1	",
	"		",
	"	r/D = 1	",
	"	r/D = 1	",
	"		",
	"	Full Line Size b = 1	",
	"	Full Line Size b = 1	",
	"	Standard b = 1	",
	"	Branch Flow	",
	"	Straight Through	",
	"	Three-Way (flow through)	",
	"	Standard b = 1	",
	"	Standard b = 1	",
	"	Dam-Type	",
	"	Vmin = 35r-1/2	",
	"	Vmin = 40r-1/2	",
	"	Non-recoverable	",
	"	Non-recoverable	"],
K1 = [	"	0	",
	"	800	",
	"	800	",
	"	800	",
	"	800	",
	"	800	",
	"	800	",
	"	1000	",
	"	800	",
	"	800	",
	"	500	",
	"	500	",
	"	500	",
	"	500	",
	"	1000	",
	"	1000	",
	"	1000	",
	"	500	",
	"	800	",
	"	800	",
	"	1000	",
	"	200	",
	"	150	",
	"	100	",
	"	950	",
	"	1000	",
	"	1500	",
	"	500	",
	"	300	",
	"	300	",
	"	300	",
	"	300	",
	"	1000	",
	"	1500	",
	"	2000	",
	"	0	",
	"	0	"],
Kinf = [	"	0	",
	"	0.14	",
	"	0.071	",
	"	0.091	",
	"	0.056	",
	"	0.066	",
	"	0.075	",
	"	0.27	",
	"	0.068	",
	"	0.035	",
	"	0.071	",
	"	0.052	",
	"	0.086	",
	"	0.052	",
	"	0.23	",
	"	0.12	",
	"	0.1	",
	"	0.274	",
	"	0.14	",
	"	0.28	",
	"	0.34	",
	"	0.091	",
	"	0.017	",
	"	0	",
	"	0.25	",
	"	0.69	",
	"	1.7	",
	"	0.41	",
	"	0.084	",
	"	0.14	",
	"	0.037	",
	"	0.017	",
	"	0.69	",
	"	0.46	",
	"	2.85	",
	"	1.5	",
	"	0	"],
Kd = [	"	0	",
	"	4	",
	"	4.2	",
	"	4	",
	"	3.9	",
	"	3.9	",
	"	4.2	",
	"	4	",
	"	4.1	",
	"	4.2	",
	"	4.2	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	4	",
	"	0	",
	"	4	",
	"	4	",
	"	3.6	",
	"	4	",
	"	3.9	",
	"	4	",
	"	3.9	",
	"	4	",
	"	4.9	",
	"	4	",
	"	3.8	",
	"	0	",
	"	0	"],
Kp = [	"	1	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	",
	"	0	"] )